Flight planner app build with in-memory repository
RLazd/flight-planner pull request #1
Opened 2022-11-07 12:25 UTC by RLazd

Sveiki. Testi darbojās, bet protams kodā varētu būt uzmabojumi.
1.Kurā līmenī jāievieto "synchronised"? Es ieliku Service līmenī.
2.Nezināju, kā klases strukturēt mapēs, tāpēc atstāju bez. Sākotnēji domāju, ka varētu izveidot controller package (kur būtu visi controller), DTOs package (kur būtu FlightRequest un SearchFlightsRequest), bet nezināju, kur ievietot pārējos failus. Tie pie šādas strukturēšanas paliktu bez atsevišķas mapes. Vai ir kāds labāks variants? 
3.AdminFlightController .addFlight() - izveidoju flight objektu jau controller līmenī. Vai tas ir pieņemami?

2022-11-20 18:54 UTC, janistumpelis requested changes
Atbildot uz jautājumiem:

`1.Kurā līmenī jāievieto "synchronised"? Es ieliku Service līmenī.` - jā tā var 👍 
`2.Nezināju, kā klases strukturēt mapēs...` - Airport un Flight var likt mapē domain, PageResult, SearchFlightsRequest, FlightRequest likt mapē dto, pārējais var palikt kopā. Iespējams kad nāks DB service un repository tad varēs uztaisīt vēl kādu mapi.
`3.AdminFlightController .addFlight() - izveidoju flight objektu jau controller līmenī. Vai tas ir pieņemami?` - jā tā ir laba vieta, kur to darīt

Bet vispār ļoti labi, paldies par darbu! 👍

2022-11-20 18:54 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/AdminFlightController.java
> +    public Flight addFlight(@Valid @RequestBody FlightRequest request, Errors errors) {
Man liekas bez tā errors var iztikt, tad viņš uzreiz teikts BadRequest, ja nebūs korekts tas FlightRequest. Tas novienkāršos kodu.

2022-11-20 18:54 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/FlightRequest.java
> +public class FlightRequest {
Šim laikam būtu korektāk saukties AddFlightRequest.

2022-11-20 18:54 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/configuration/SecurityConfiguration.java
> +                .csrf().disable() //disables CSRF protection
Komentārus laikam būtu labāk noņemt, lai nav visiem vienādi.

2022-11-25 14:50 UTC, RLazd commented on src/main/java/io/codelex/flightplanner/AdminFlightController.java
> +    public Flight addFlight(@Valid @RequestBody FlightRequest request, Errors errors) {
Ja vienkārši noņēmu, negāja (tur bija jāatgriež dazādi 400 kodi, atkarībā no problēmas). Ieliku try/catch blokā ( bet neesmu pārliecināta, ka šis izskatās labāk :D.. kā tev liekas?)

2022-11-26 07:02 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/AdminFlightController.java
> +    public Flight addFlight(@Valid @RequestBody FlightRequest request, Errors errors) {
Tev jau tie kodi ir pareizi sarakstīti iekš service, man liekas tur visam būtu jāstrādā. Bet kas par kļūdu var notikt veidojot jaunu flight objektu, ka ieliki to try/catch?
Bet vispār likšu approve, lai vari normāli veidot DB variantu, šo var pielabot vēlāk.

2022-11-26 07:02 UTC, janistumpelis approved these changes

2022-11-29 06:36 UTC, merged